// constants.ts
export const DEFAULT_SOL_ADDRESS = process.env.REACT_APP_DEFAULT_SOL_ADDRESS || "DEFAULT_FALLBACK_ADDRESS";
export const SOLANA_MAINNET_USDC_PUBKEY = process.env.REACT_APP_USDC_TOKEN_PUBLIC_KEY || "DEFAULT_FALLBACK_USDC_KEY";
